package com.example.myapp;

import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class MyApp extends Lifecycle {
	Form hi;
	
    @Override
    public void runApp() {
    	hi = new Form("ViewRlv", BoxLayout.y()) {
		};
		
		SpanArea fieldArea = new SpanArea();
		fieldArea.addTextField("txt1");
		fieldArea.addTextField("txt2");
		fieldArea.addTextField("txt3");
		
		hi.add(fieldArea);
		hi.setFocusable(false);
        hi.show();   	
    }
    
}
